name: Build image
on:
  [push]
jobs:
  build-image:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
    env:
      DOCKER_USERNAME: gitea
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      
      - name: Login to gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.mb-server.com
          username: mb
          password: ${{ secrets.DOCKER_TOKEN_MORE  }}
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64                                                
          push: true
          tags: git.mb-server.com/schoolware-nextgen/schoolware-backend:latest
      - name: deploy coolify
        run: |
          curl --request GET \
          --url 'http://192.168.0.168:8000/api/v1/deploy?uuid=i8g0k884wkcw88k0ggokokgg&force=false' \
          --header 'Authorization: Bearer ${{ secrets.COOLIFYTOKEN   }}' \
          --header 'User-Agent: insomnia/9.3.2'